/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/repositories` | `/repositories`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/repositories/issues` | `/repositories/issues`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/repositories/styles` | `/repositories/styles`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/repositories/[id]` | `/repositories/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/repositories` | `/repositories`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/repositories/issues` | `/repositories/issues`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/repositories/styles` | `/repositories/styles`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/repositories/[id]` | `/repositories/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(app)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/repositories${`?${string}` | `#${string}` | ''}` | `/repositories${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/repositories/issues${`?${string}` | `#${string}` | ''}` | `/repositories/issues${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/repositories/styles${`?${string}` | `#${string}` | ''}` | `/repositories/styles${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/repositories` | `/repositories`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/repositories/issues` | `/repositories/issues`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/repositories/styles` | `/repositories/styles`; params?: Router.UnknownInputParams; } | `${'/(app)'}/repositories/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/repositories/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `${'/(app)'}/repositories/[id]` | `/repositories/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
